title: Jia Xing # your name (or website title) here
logo: "/images/Pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  7 Years banking experience in banking collection/credit departments. Mid-career change with deep interest in data analytics and machine learning. Adept at learning new concepts and applying acquired knowledge to business functions. 
  <br><br>
  <a href="https://www.linkedin.com/in/tayjiaxing/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
